[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_vault_prototype = "HaryVUcfDqxpzFS7JyNe1XuqscFWyYFVAJdYoUX6jEcS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
